version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: lexicon-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token_authn.TokenAuthenticationProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS=test-token
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
      - ANONYMIZED_TELEMETRY=false
    networks:
      - lexicon-network

  redis:
    image: redis:7-alpine
    container_name: lexicon-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - lexicon-network

networks:
  lexicon-network:
    driver: bridge

volumes:
  chroma-data:
  redis-data: