version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: lexicon-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - webapp
      - chromadb
    networks:
      - lexicon-network
    restart: unless-stopped

  # ChromaDB vector database
  chromadb:
    image: chromadb/chroma:latest
    container_name: lexicon-chromadb
    ports:
      - "8100:8000"
    volumes:
      - lexicon-chroma-data:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=false
    networks:
      - lexicon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: lexicon-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis-local.conf:/usr/local/etc/redis/redis.conf
      - lexicon-redis-data:/data
    networks:
      - lexicon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main web application
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lexicon-webapp
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./generated-briefs:/app/generated-briefs
    depends_on:
      - chromadb
      - redis
    networks:
      - lexicon-network
    restart: unless-stopped

networks:
  lexicon-network:
    driver: bridge

volumes:
  lexicon-chroma-data:
  lexicon-redis-data: